INSERT INTO product (id, name, description, price, type) VALUES
(1, 'Widget A', 'High-quality widget for everyday use', 19.99, 'Widget'),
(2, 'Gadget B', 'Advanced gadget with multiple functions', 49.99, 'Gadget'),
(3, 'Tool C', 'Durable tool for professional use', 39.99, 'Tool'),
(4, 'Device D', 'Smart device with IoT capabilities', 99.99, 'Device'),
(5, 'Accessory E', 'Accessory compatible with various devices', 9.99, 'Accessory'),
(6, 'Widget F', 'Compact widget for travel', 14.99, 'Widget'),
(7, 'Gadget G', 'Entertainment gadget with VR support', 79.99, 'Gadget'),
(8, 'Tool H', 'Versatile tool set for DIY projects', 59.99, 'Tool'),
(9, 'Device I', 'Smartphone with AI features', 399.99, 'Device'),
(10, 'Accessory J', 'Fashionable accessory for everyday wear', 29.99, 'Accessory'),
(11, 'Widget K', 'Customizable widget for personal use', 24.99, 'Widget'),
(12, 'Gadget L', 'Outdoor gadget for adventurous activities', 129.99, 'Gadget'),
(13, 'Tool M', 'Precision tool for industrial applications', 149.99, 'Tool'),
(14, 'Device N', 'Tablet with high-resolution display', 299.99, 'Device'),
(15, 'Accessory O', 'Functional accessory for fitness tracking', 19.99, 'Accessory'),
(16, 'Widget P', 'Eco-friendly widget made from recycled materials', 17.99, 'Widget'),
(17, 'Gadget Q', 'Smart gadget with voice assistant support', 89.99, 'Gadget'),
(18, 'Tool R', 'Heavy-duty tool set for construction', 199.99, 'Tool'),
(19, 'Device S', 'Laptop with fast processing power', 799.99, 'Device'),
(20, 'Accessory T', 'Stylish accessory for special occasions', 39.99, 'Accessory'),
(21, 'Widget U', 'Child-friendly widget for educational purposes', 12.99, 'Widget'),
(22, 'Gadget V', 'Compact gadget for on-the-go use', 69.99, 'Gadget'),
(23, 'Tool W', 'Multi-functional tool for household repairs', 29.99, 'Tool'),
(24, 'Device X', 'Smartwatch with health monitoring features', 199.99, 'Device'),
(25, 'Accessory Y', 'Tech accessory for mobile devices', 14.99, 'Accessory'),
(26, 'Widget Z', 'Futuristic widget with advanced features', 34.99, 'Widget'),
(27, 'Gadget AA', 'Gadget with augmented reality capabilities', 149.99, 'Gadget'),
(28, 'Tool BB', 'Professional tool kit for mechanics', 249.99, 'Tool'),
(29, 'Device CC', 'High-end smartphone with 5G support', 999.99, 'Device'),
(30, 'Accessory DD', 'Practical accessory for outdoor activities', 24.99, 'Accessory'),
(31, 'Widget EE', 'Compact widget with energy-saving features', 22.99, 'Widget'),
(32, 'Gadget FF', 'Entertainment gadget with HD display', 179.99, 'Gadget'),
(33, 'Tool GG', 'Portable tool set for emergencies', 39.99, 'Tool'),
(34, 'Device HH', 'Powerful desktop computer for gaming', 1499.99, 'Device'),
(35, 'Accessory II', 'Accessory for enhancing audio experience', 49.99, 'Accessory'),
(36, 'Widget JJ', 'Modular widget with customizable parts', 44.99, 'Widget'),
(37, 'Gadget KK', 'Outdoor gadget with GPS navigation', 199.99, 'Gadget'),
(38, 'Tool LL', 'Robust tool set for heavy-duty tasks', 349.99, 'Tool'),
(39, 'Device MM', 'Convertible laptop with touch screen', 1299.99, 'Device'),
(40, 'Accessory NN', 'Fashionable accessory for tech enthusiasts', 19.99, 'Accessory'),
(41, 'Widget OO', 'Smart widget with wireless connectivity', 29.99, 'Widget'),
(42, 'Gadget PP', 'Smart home gadget with automation features', 249.99, 'Gadget'),
(43, 'Tool QQ', 'Toolbox with various essential tools', 79.99, 'Tool'),
(44, 'Device RR', 'Ultra-thin laptop with long battery life', 1699.99, 'Device'),
(45, 'Accessory SS', 'Accessory for improving productivity', 34.99, 'Accessory'),
(46, 'Widget TT', 'Eco-friendly widget made from sustainable materials', 19.99, 'Widget'),
(47, 'Gadget UU', 'Portable gadget with extended battery life', 109.99, 'Gadget'),
(48, 'Tool VV', 'Precision tool set for delicate work', 89.99, 'Tool'),
(49, 'Device WW', 'Gaming console with 4K gaming support', 499.99, 'Device'),
(50, 'Accessory XX', 'Accessory for enhancing photography', 29.99, 'Accessory'),
(51, 'Widget YY', 'Widget designed for medical applications', 49.99, 'Widget'),
(52, 'Gadget ZZ', 'Waterproof gadget for underwater activities', 179.99, 'Gadget'),
(53, 'Tool AAA', 'Tool kit for automotive repairs', 159.99, 'Tool'),
(54, 'Device BBB', 'Smart speaker with voice control', 79.99, 'Device'),
(55, 'Accessory CCC', 'Stylish accessory for fashion-conscious users', 39.99, 'Accessory'),
(56, 'Widget DDD', 'Compact widget for educational purposes', 14.99, 'Widget'),
(57, 'Gadget EEE', 'Entertainment gadget with surround sound', 199.99, 'Gadget'),
(58, 'Tool FFF', 'Tool set for woodworking projects', 69.99, 'Tool'),
(59, 'Device GGG', 'Smart TV with streaming capabilities', 799.99, 'Device'),
(60, 'Accessory HHH', 'Accessory for enhancing gaming experience', 49.99, 'Accessory'),
(61, 'Widget III', 'Widget with advanced AI integration', 79.99, 'Widget'),
(62, 'Gadget JJJ', 'Gadget with infrared night vision', 299.99, 'Gadget'),
(63, 'Tool KKK', 'Heavy-duty tool set for construction sites', 399.99, 'Tool'),
(64, 'Device LLL', 'Tablet with stylus for creative work', 599.99, 'Device'),
(65, 'Accessory MMM', 'Accessory for travelers', 24.99, 'Accessory'),
(66, 'Widget NNN', 'Widget designed for seniors', 29.99, 'Widget'),
(67, 'Gadget OOO', 'Gadget for outdoor enthusiasts', 149.99, 'Gadget'),
(68, 'Tool PPP', 'Tool set for home improvement projects', 49.99, 'Tool'),
(69, 'Device QQQ', 'Laptop with ergonomic design', 899.99, 'Device'),
(70, 'Accessory RRR', 'Accessory for enhancing productivity', 19.99, 'Accessory'),
(71, 'Widget SSS', 'Widget with customizable interface', 39.99, 'Widget'),
(72, 'Gadget TTT', 'Gadget with built-in camera', 129.99, 'Gadget'),
(73, 'Tool UUU', 'Tool set for electrical repairs', 79.99, 'Tool'),
(74, 'Device VVV', 'Smartphone with advanced camera features', 699.99, 'Device'),
(75, 'Accessory WWW', 'Accessory for fitness tracking', 29.99, 'Accessory'),
(76, 'Widget XXX', 'Widget with temperature control', 59.99, 'Widget'),
(77, 'Gadget YYY', 'Gadget for pet care', 89.99, 'Gadget'),
(78, 'Tool ZZZ', 'Tool set for plumbing', 99.99, 'Tool'),
(79, 'Device AAAA', 'Smartwatch with health monitoring', 299.99, 'Device'),
(80, 'Accessory BBBB', 'Fashionable accessory for everyday use', 14.99, 'Accessory'),
(81, 'Widget CCCC', 'Widget with voice recognition', 49.99, 'Widget'),
(82, 'Gadget DDDD', 'Gadget for home security', 179.99, 'Gadget'),
(83, 'Tool EEEE', 'Tool set for car maintenance', 129.99, 'Tool'),
(84, 'Device FFFF', 'Tablet with fast processor', 499.99, 'Device'),
(85, 'Accessory GGGG', 'Accessory for mobile devices', 9.99, 'Accessory'),
(86, 'Widget HHHH', 'Widget with gesture control', 69.99, 'Widget'),
(87, 'Gadget IIII', 'Gadget for underwater exploration', 249.99, 'Gadget'),
(88, 'Tool JJJJ', 'Tool set for woodworking', 89.99, 'Tool'),
(89, 'Device KKKK', 'Gaming laptop with high refresh rate', 1299.99, 'Device'),
(90, 'Accessory LLLL', 'Accessory for enhancing audio experience', 24.99, 'Accessory');

-- Add more INSERT statements as needed
